### ISSUE TITLE
Activate features per source file

### ISSUE THREAD

**Issue by marler8997** [marler8997/dc#61]
Provide a way to activate new features.  We could piggyback off the `version` feature for this, i.e.
```D
version = D3;

// I'm using new D3 features...yeay
```

**Comment by wilzbach** [comment]
Non-complete list of things which this flag should activate.

- [ ] https://github.com/marler8997/dc/issues/39 (classes should be final by default)
- [ ] https://github.com/marler8997/dc/issues/36 (remove Object.factory)
- [ ] https://github.com/marler8997/dc/issues/32 (@safe by default)
- [ ] https://github.com/marler8997/dc/issues/22 (no imaginary & complex types)
...

**Comment by ntrel** [comment]
`scope` should be the default for parameters, and have e.g. `@escape` to mark escaping parameters.
